databases:
  - name: recipe_db
    databaseName: recipe_db
    user: recipe_user
    plan: free

services:
  - type: web
    name: recipe-app
    runtime: python
    startCommand: bash build.sh && gunicorn config.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DEBUG
        value: "False"
